import type { Metadata } from "next";
import { Ubuntu, Lato } from "next/font/google";
import Link from 'next/link'
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "900"], // normal + bold
  variable: "--font-sans",
  display: "swap",
});

const second = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "700"], // normal + bold
  variable: "--font-heading",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${second.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
